<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CardmarketExpansionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $expansions = [
            ['cardmarket_expansion_id' => 1606, 'name' => '"W" Promos'],
            ['cardmarket_expansion_id' => 5402, 'name' => '151'],
            ['cardmarket_expansion_id' => 5912, 'name' => '151: Scarlet & Violet Etched'],
            ['cardmarket_expansion_id' => 5911, 'name' => '151: Scarlet & Violet Ultra-Premium Collection'],
            ['cardmarket_expansion_id' => 1621, 'name' => 'Ancient Origins'],
            ['cardmarket_expansion_id' => 4732, 'name' => 'Astral Radiance'],
            ['cardmarket_expansion_id' => 4815, 'name' => 'Astral Radiance: Trainer Gallery'],
            ['cardmarket_expansion_id' => 1613, 'name' => 'Base Set'],
            ['cardmarket_expansion_id' => 1728, 'name' => 'Base Set 2'],
            ['cardmarket_expansion_id' => 1714, 'name' => 'Base Set Shadowless'],
            ['cardmarket_expansion_id' => 1614, 'name' => 'Battle Styles'],
            ['cardmarket_expansion_id' => 4554, 'name' => 'Battle Styles: Single Strike'],
            ['cardmarket_expansion_id' => 4555, 'name' => 'Battle Styles: Single Strike Urshifu V-UNION'],
            ['cardmarket_expansion_id' => 1604, 'name' => 'Best of Game'],
            ['cardmarket_expansion_id' => 1757, 'name' => 'Black & White'],
            ['cardmarket_expansion_id' => 1798, 'name' => 'Black & White Promos'],
            ['cardmarket_expansion_id' => 1760, 'name' => 'Black Star Promos'],
            ['cardmarket_expansion_id' => 1623, 'name' => 'Boundaries Crossed'],
            ['cardmarket_expansion_id' => 1625, 'name' => 'BREAKpoint'],
            ['cardmarket_expansion_id' => 1624, 'name' => 'BREAKthrough'],
            ['cardmarket_expansion_id' => 5058, 'name' => 'Brilliant Stars'],
            ['cardmarket_expansion_id' => 5060, 'name' => 'Brilliant Stars: Trainer Gallery'],
            ['cardmarket_expansion_id' => 1643, 'name' => 'Burning Shadows'],
            ['cardmarket_expansion_id' => 1628, 'name' => 'Call of Legends'],
            ['cardmarket_expansion_id' => 5669, 'name' => 'Champion\'s Path'],
            ['cardmarket_expansion_id' => 1631, 'name' => 'Chilling Reign'],
            ['cardmarket_expansion_id' => 1730, 'name' => 'Classic Collection'],
            ['cardmarket_expansion_id' => 6419, 'name' => 'Classic: Scarlet & Violet'],
            ['cardmarket_expansion_id' => 1632, 'name' => 'Cosmic Eclipse'],
            ['cardmarket_expansion_id' => 1741, 'name' => 'Crane Game FD Promos'],
            ['cardmarket_expansion_id' => 1633, 'name' => 'Crimson Invasion'],
            ['cardmarket_expansion_id' => 1634, 'name' => 'Dark Explorers'],
            ['cardmarket_expansion_id' => 1636, 'name' => 'Darkness Ablaze'],
            ['cardmarket_expansion_id' => 1737, 'name' => 'DPt Promos'],
            ['cardmarket_expansion_id' => 1638, 'name' => 'Dragon Majesty'],
            ['cardmarket_expansion_id' => 1639, 'name' => 'Dragons Exalted'],
            ['cardmarket_expansion_id' => 1640, 'name' => 'Emerging Powers'],
            ['cardmarket_expansion_id' => 6127, 'name' => 'Eevee Heroes'],
            ['cardmarket_expansion_id' => 1641, 'name' => 'Evolutions'],
            ['cardmarket_expansion_id' => 1726, 'name' => 'EX Battle Boost'],
            ['cardmarket_expansion_id' => 1642, 'name' => 'EX Crystal Guardians'],
            ['cardmarket_expansion_id' => 1796, 'name' => 'EX Deoxys'],
            ['cardmarket_expansion_id' => 1795, 'name' => 'EX Dragon'],
            ['cardmarket_expansion_id' => 1794, 'name' => 'EX Dragon Frontiers'],
            ['cardmarket_expansion_id' => 1793, 'name' => 'EX Emerald'],
            ['cardmarket_expansion_id' => 1792, 'name' => 'EX FireRed & LeafGreen'],
            ['cardmarket_expansion_id' => 1791, 'name' => 'EX Hidden Legends'],
            ['cardmarket_expansion_id' => 1790, 'name' => 'EX Holon Phantoms'],
            ['cardmarket_expansion_id' => 1789, 'name' => 'EX Legend Maker'],
            ['cardmarket_expansion_id' => 1788, 'name' => 'EX Power Keepers'],
            ['cardmarket_expansion_id' => 1787, 'name' => 'EX Ruby & Sapphire'],
            ['cardmarket_expansion_id' => 1786, 'name' => 'EX Sandstorm'],
            ['cardmarket_expansion_id' => 1785, 'name' => 'EX Team Magma vs Team Aqua'],
            ['cardmarket_expansion_id' => 1784, 'name' => 'EX Team Rocket Returns'],
            ['cardmarket_expansion_id' => 1783, 'name' => 'EX Unseen Forces'],
            ['cardmarket_expansion_id' => 1762, 'name' => 'Evolving Skies'],
            ['cardmarket_expansion_id' => 1782, 'name' => 'Expedition'],
            ['cardmarket_expansion_id' => 1644, 'name' => 'Fates Collide'],
            ['cardmarket_expansion_id' => 1645, 'name' => 'Flashfire'],
            ['cardmarket_expansion_id' => 1646, 'name' => 'Forbidden Light'],
            ['cardmarket_expansion_id' => 1735, 'name' => 'Fossil'],
            ['cardmarket_expansion_id' => 1647, 'name' => 'Furious Fists'],
            ['cardmarket_expansion_id' => 5182, 'name' => 'Fusion Strike'],
            ['cardmarket_expansion_id' => 1648, 'name' => 'Fusion Strike: Single Strike & Rapid Strike'],
            ['cardmarket_expansion_id' => 1649, 'name' => 'Generations'],
            ['cardmarket_expansion_id' => 1650, 'name' => 'Generations: Radiant Collection'],
            ['cardmarket_expansion_id' => 1651, 'name' => 'Great Encounters'],
            ['cardmarket_expansion_id' => 1652, 'name' => 'Guardians Rising'],
            ['cardmarket_expansion_id' => 1653, 'name' => 'HeartGold SoulSilver'],
            ['cardmarket_expansion_id' => 1781, 'name' => 'HeartGold SoulSilver Promos'],
            ['cardmarket_expansion_id' => 1780, 'name' => 'Hidden Fates'],
            ['cardmarket_expansion_id' => 1655, 'name' => 'Hidden Fates: Shiny Vault'],
            ['cardmarket_expansion_id' => 1779, 'name' => 'HS Triumphant'],
            ['cardmarket_expansion_id' => 1778, 'name' => 'HS Undaunted'],
            ['cardmarket_expansion_id' => 1777, 'name' => 'HS Unleashed'],
            ['cardmarket_expansion_id' => 1776, 'name' => 'HGSS Black Star Promos'],
            ['cardmarket_expansion_id' => 1656, 'name' => 'Jungle'],
            ['cardmarket_expansion_id' => 5668, 'name' => 'Kalos Starter Set'],
            ['cardmarket_expansion_id' => 1773, 'name' => 'Legendary Collection'],
            ['cardmarket_expansion_id' => 1658, 'name' => 'Legendary Treasures'],
            ['cardmarket_expansion_id' => 1659, 'name' => 'Legendary Treasures: Radiant Collection'],
            ['cardmarket_expansion_id' => 1660, 'name' => 'Legends Awakened'],
            ['cardmarket_expansion_id' => 5667, 'name' => 'Light & Darkness'],
            ['cardmarket_expansion_id' => 1661, 'name' => 'Lost Origin'],
            ['cardmarket_expansion_id' => 4930, 'name' => 'Lost Origin: Trainer Gallery'],
            ['cardmarket_expansion_id' => 1662, 'name' => 'Lost Thunder'],
            ['cardmarket_expansion_id' => 1663, 'name' => 'Majestic Dawn'],
            ['cardmarket_expansion_id' => 1771, 'name' => 'McDonald\'s Collection 2011'],
            ['cardmarket_expansion_id' => 1770, 'name' => 'McDonald\'s Collection 2012'],
            ['cardmarket_expansion_id' => 1769, 'name' => 'McDonald\'s Collection 2014'],
            ['cardmarket_expansion_id' => 1768, 'name' => 'McDonald\'s Collection 2015'],
            ['cardmarket_expansion_id' => 1767, 'name' => 'McDonald\'s Collection 2016'],
            ['cardmarket_expansion_id' => 1766, 'name' => 'McDonald\'s Collection 2017'],
            ['cardmarket_expansion_id' => 1765, 'name' => 'McDonald\'s Collection 2018'],
            ['cardmarket_expansion_id' => 1764, 'name' => 'McDonald\'s Collection 2019'],
            ['cardmarket_expansion_id' => 3948, 'name' => 'McDonald\'s Collection 2021'],
            ['cardmarket_expansion_id' => 4810, 'name' => 'McDonald\'s Collection 2022'],
            ['cardmarket_expansion_id' => 5593, 'name' => 'McDonald\'s Collection 2023'],
            ['cardmarket_expansion_id' => 6246, 'name' => 'McDonald\'s Collection 2024'],
            ['cardmarket_expansion_id' => 1664, 'name' => 'Mysterious Treasures'],
            ['cardmarket_expansion_id' => 1665, 'name' => 'Neo Destiny'],
            ['cardmarket_expansion_id' => 1763, 'name' => 'Neo Discovery'],
            ['cardmarket_expansion_id' => 1761, 'name' => 'Neo Genesis'],
            ['cardmarket_expansion_id' => 1759, 'name' => 'Neo Revelation'],
            ['cardmarket_expansion_id' => 1666, 'name' => 'Next Destinies'],
            ['cardmarket_expansion_id' => 1667, 'name' => 'Noble Victories'],
            ['cardmarket_expansion_id' => 5800, 'name' => 'Obsidian Flames'],
            ['cardmarket_expansion_id' => 1668, 'name' => 'Other Cards'],
            ['cardmarket_expansion_id' => 5844, 'name' => 'Paldea Evolved'],
            ['cardmarket_expansion_id' => 5845, 'name' => 'Paldea Evolved: Scarlet & Violet'],
            ['cardmarket_expansion_id' => 6036, 'name' => 'Paldean Fates'],
            ['cardmarket_expansion_id' => 1669, 'name' => 'Phantom Forces'],
            ['cardmarket_expansion_id' => 1670, 'name' => 'Plasma Blast'],
            ['cardmarket_expansion_id' => 1671, 'name' => 'Plasma Freeze'],
            ['cardmarket_expansion_id' => 1672, 'name' => 'Plasma Storm'],
            ['cardmarket_expansion_id' => 3758, 'name' => 'Pokémon GO'],
            ['cardmarket_expansion_id' => 1673, 'name' => 'Primal Clash'],
            ['cardmarket_expansion_id' => 1675, 'name' => 'Promo Cards'],
            ['cardmarket_expansion_id' => 1676, 'name' => 'Rebel Clash'],
            ['cardmarket_expansion_id' => 1756, 'name' => 'Roaring Skies'],
            ['cardmarket_expansion_id' => 1755, 'name' => 'Sandstorm'],
            ['cardmarket_expansion_id' => 5521, 'name' => 'Scarlet & Violet'],
            ['cardmarket_expansion_id' => 1678, 'name' => 'Secret Wonders'],
            ['cardmarket_expansion_id' => 1679, 'name' => 'Shining Fates'],
            ['cardmarket_expansion_id' => 4164, 'name' => 'Shining Fates: Shiny Vault'],
            ['cardmarket_expansion_id' => 4934, 'name' => 'Silver Tempest'],
            ['cardmarket_expansion_id' => 4933, 'name' => 'Silver Tempest: Trainer Gallery'],
            ['cardmarket_expansion_id' => 1754, 'name' => 'Skyridge'],
            ['cardmarket_expansion_id' => 1680, 'name' => 'SM Base Set'],
            ['cardmarket_expansion_id' => 1681, 'name' => 'SM Black Star Promos'],
            ['cardmarket_expansion_id' => 1682, 'name' => 'Southern Islands'],
            ['cardmarket_expansion_id' => 1683, 'name' => 'Steam Siege'],
            ['cardmarket_expansion_id' => 1684, 'name' => 'Stormfront'],
            ['cardmarket_expansion_id' => 6304, 'name' => 'Surging Sparks'],
            ['cardmarket_expansion_id' => 1753, 'name' => 'SWSH Base Set'],
            ['cardmarket_expansion_id' => 1685, 'name' => 'SWSH Black Star Promos'],
            ['cardmarket_expansion_id' => 1686, 'name' => 'Team Up'],
            ['cardmarket_expansion_id' => 1752, 'name' => 'Team Magma vs Team Aqua'],
            ['cardmarket_expansion_id' => 1687, 'name' => 'Team Plasma'],
            ['cardmarket_expansion_id' => 1751, 'name' => 'Team Rocket'],
            ['cardmarket_expansion_id' => 6166, 'name' => 'Temporal Forces'],
            ['cardmarket_expansion_id' => 1688, 'name' => 'The "Gym" Series'],
            ['cardmarket_expansion_id' => 1689, 'name' => 'Trainer Kit: Alolan Raichu & Lycanroc'],
            ['cardmarket_expansion_id' => 1690, 'name' => 'Trainer Kit: Latias & Latios'],
            ['cardmarket_expansion_id' => 1691, 'name' => 'Trainer Kit: Pikachu Libre & Suicune'],
            ['cardmarket_expansion_id' => 1692, 'name' => 'Triumphant'],
            ['cardmarket_expansion_id' => 6088, 'name' => 'Twilight Masquerade'],
            ['cardmarket_expansion_id' => 1693, 'name' => 'Ultra Prism'],
            ['cardmarket_expansion_id' => 1694, 'name' => 'Undaunted'],
            ['cardmarket_expansion_id' => 1695, 'name' => 'Unified Minds'],
            ['cardmarket_expansion_id' => 1696, 'name' => 'Unleashed'],
            ['cardmarket_expansion_id' => 1697, 'name' => 'Unbroken Bonds'],
            ['cardmarket_expansion_id' => 1699, 'name' => 'Unseen Forces'],
            ['cardmarket_expansion_id' => 1700, 'name' => 'Vivid Voltage'],
            ['cardmarket_expansion_id' => 1750, 'name' => 'VS Series'],
            ['cardmarket_expansion_id' => 5697, 'name' => 'VSTAR Universe'],
            ['cardmarket_expansion_id' => 5696, 'name' => 'VSTAR Universe: Character Rares'],
            ['cardmarket_expansion_id' => 1749, 'name' => 'WotC Black Star Promos'],
            ['cardmarket_expansion_id' => 1701, 'name' => 'XY'],
            ['cardmarket_expansion_id' => 1702, 'name' => 'XY Black Star Promos'],
            ['cardmarket_expansion_id' => 1703, 'name' => 'XY Trainer Kit: Latias & Latios'],
            ['cardmarket_expansion_id' => 1704, 'name' => 'XY Trainer Kit: Pikachu Libre & Suicune'],
            ['cardmarket_expansion_id' => 1748, 'name' => 'XY Trainer Kit: Wigglytuff & Noivern'],
            ['cardmarket_expansion_id' => 1747, 'name' => 'XY Base Set'],
            ['cardmarket_expansion_id' => 1746, 'name' => 'XY BREAKpoint'],
            ['cardmarket_expansion_id' => 1745, 'name' => 'XY BREAKthrough'],
            ['cardmarket_expansion_id' => 1744, 'name' => 'XY Ancient Origins'],
            ['cardmarket_expansion_id' => 1743, 'name' => 'XY Evolutions'],
            ['cardmarket_expansion_id' => 1742, 'name' => 'XY Fates Collide'],
            ['cardmarket_expansion_id' => 1740, 'name' => 'XY Flashfire'],
            ['cardmarket_expansion_id' => 1739, 'name' => 'XY Furious Fists'],
            ['cardmarket_expansion_id' => 1738, 'name' => 'XY Phantom Forces'],
            ['cardmarket_expansion_id' => 1736, 'name' => 'XY Primal Clash'],
            ['cardmarket_expansion_id' => 1734, 'name' => 'XY Roaring Skies'],
            ['cardmarket_expansion_id' => 1733, 'name' => 'XY Steam Siege'],
            ['cardmarket_expansion_id' => 5666, 'name' => 'Japanese Miscellaneous Cards'],
            ['cardmarket_expansion_id' => 1521, 'name' => 'Meiji Promos'],
            ['cardmarket_expansion_id' => 5979, 'name' => 'Raging Surf'],
            ['cardmarket_expansion_id' => 5978, 'name' => 'Snow Hazard & Clay Burst'],
            ['cardmarket_expansion_id' => 5976, 'name' => 'Pokémon Card 151'],
            ['cardmarket_expansion_id' => 6095, 'name' => 'Wild Force & Cyber Judge'],
            ['cardmarket_expansion_id' => 5975, 'name' => 'Triplet Beat'],
            ['cardmarket_expansion_id' => 5974, 'name' => 'Ancient Roar & Future Flash'],
            ['cardmarket_expansion_id' => 5973, 'name' => 'Ruler of the Black Flame'],
            ['cardmarket_expansion_id' => 5972, 'name' => 'Scarlet ex'],
            ['cardmarket_expansion_id' => 5971, 'name' => 'Violet ex'],
            ['cardmarket_expansion_id' => 6128, 'name' => 'Eevee Heroes: Eevee\'s'],
            ['cardmarket_expansion_id' => 5970, 'name' => 'Incandescent Arcana'],
            ['cardmarket_expansion_id' => 5969, 'name' => 'Lost Abyss'],
            ['cardmarket_expansion_id' => 5968, 'name' => 'Dark Phantasma'],
            ['cardmarket_expansion_id' => 5967, 'name' => 'Pokémon GO (Japan)'],
            ['cardmarket_expansion_id' => 5966, 'name' => 'Space Juggler'],
            ['cardmarket_expansion_id' => 5965, 'name' => 'Time Gazer'],
            ['cardmarket_expansion_id' => 5964, 'name' => 'Battle Region'],
            ['cardmarket_expansion_id' => 5963, 'name' => 'Star Birth'],
            ['cardmarket_expansion_id' => 5962, 'name' => 'Fusion Arts'],
            ['cardmarket_expansion_id' => 5961, 'name' => 'Blue Sky Stream'],
            ['cardmarket_expansion_id' => 5960, 'name' => 'Skyscraping Perfection'],
            ['cardmarket_expansion_id' => 5959, 'name' => 'Jet Black Geist'],
            ['cardmarket_expansion_id' => 5958, 'name' => 'Silver Lance'],
            ['cardmarket_expansion_id' => 5957, 'name' => 'Peerless Fighters'],
            ['cardmarket_expansion_id' => 5956, 'name' => 'Eevee Heroes (Japan)'],
            ['cardmarket_expansion_id' => 5955, 'name' => 'Matchless Fighters'],
            ['cardmarket_expansion_id' => 5954, 'name' => 'Jet-Black Poltergeist'],
            ['cardmarket_expansion_id' => 5953, 'name' => 'Silver Lance (Japan)'],
            ['cardmarket_expansion_id' => 5952, 'name' => 'Matchless Perfection'],
            ['cardmarket_expansion_id' => 5951, 'name' => 'Legendary Heartbeat'],
            ['cardmarket_expansion_id' => 5950, 'name' => 'Explosive Walker'],
            ['cardmarket_expansion_id' => 5949, 'name' => 'Infinity Zone'],
            ['cardmarket_expansion_id' => 5948, 'name' => 'Rebellion Crash'],
            ['cardmarket_expansion_id' => 5947, 'name' => 'Explosive Flame Walker'],
            ['cardmarket_expansion_id' => 5946, 'name' => 'Mugen Zone'],
            ['cardmarket_expansion_id' => 5945, 'name' => 'VMAX Rising'],
            ['cardmarket_expansion_id' => 5944, 'name' => 'Sword'],
            ['cardmarket_expansion_id' => 5943, 'name' => 'Shield'],
            ['cardmarket_expansion_id' => 5942, 'name' => 'Alter Genesis'],
            ['cardmarket_expansion_id' => 5941, 'name' => 'Dream League'],
            ['cardmarket_expansion_id' => 5940, 'name' => 'Remix Bout'],
            ['cardmarket_expansion_id' => 5939, 'name' => 'Miracle Twin'],
            ['cardmarket_expansion_id' => 5938, 'name' => 'Sky Legend'],
            ['cardmarket_expansion_id' => 5937, 'name' => 'Night Unison'],
            ['cardmarket_expansion_id' => 5936, 'name' => 'Double Blaze'],
            ['cardmarket_expansion_id' => 5935, 'name' => 'Tag Bolt'],
            ['cardmarket_expansion_id' => 5934, 'name' => 'Full Metal Wall'],
            ['cardmarket_expansion_id' => 5933, 'name' => 'Tag Team GX All Stars'],
            ['cardmarket_expansion_id' => 5932, 'name' => 'Night Unison: Character Rares'],
            ['cardmarket_expansion_id' => 5931, 'name' => 'GG End'],
            ['cardmarket_expansion_id' => 5930, 'name' => 'Sky Legend: Character Rares'],
            ['cardmarket_expansion_id' => 5929, 'name' => 'Double Blaze: Character Rares'],
            ['cardmarket_expansion_id' => 5928, 'name' => 'Dragon Storm'],
            ['cardmarket_expansion_id' => 5927, 'name' => 'Champion Road'],
            ['cardmarket_expansion_id' => 5926, 'name' => 'Fairy Rise'],
            ['cardmarket_expansion_id' => 5925, 'name' => 'SM-P Promotional cards'],
            ['cardmarket_expansion_id' => 5924, 'name' => 'Thunderclap Spark'],
            ['cardmarket_expansion_id' => 5923, 'name' => 'GX Ultra Shiny'],
            ['cardmarket_expansion_id' => 5922, 'name' => 'Explosive Impact'],
            ['cardmarket_expansion_id' => 5921, 'name' => 'Dark Order'],
            ['cardmarket_expansion_id' => 5920, 'name' => 'Sky-Splitting Charisma'],
            ['cardmarket_expansion_id' => 5919, 'name' => 'Awakened Heroes'],
            ['cardmarket_expansion_id' => 5918, 'name' => 'Ultra Moon'],
            ['cardmarket_expansion_id' => 5917, 'name' => 'Ultra Sun'],
            ['cardmarket_expansion_id' => 5916, 'name' => 'Ultra Force'],
            ['cardmarket_expansion_id' => 5915, 'name' => 'Ultra Shiny: Shiny Vault'],
            ['cardmarket_expansion_id' => 5914, 'name' => 'Shining Legends'],
            ['cardmarket_expansion_id' => 5913, 'name' => 'Crimson Invasion (Japan)'],
            ['cardmarket_expansion_id' => 5910, 'name' => 'Burning Shadows (Japan)'],
            ['cardmarket_expansion_id' => 5909, 'name' => 'Darkness that Consumes Light'],
            ['cardmarket_expansion_id' => 5908, 'name' => 'To Have Seen the Battle Rainbow'],
            ['cardmarket_expansion_id' => 5907, 'name' => 'Guardians Rising (Japan)'],
            ['cardmarket_expansion_id' => 5906, 'name' => 'Islands Await You'],
            ['cardmarket_expansion_id' => 5905, 'name' => 'Alolan Moonlight'],
            ['cardmarket_expansion_id' => 5904, 'name' => 'Collection Sun'],
            ['cardmarket_expansion_id' => 5903, 'name' => 'Collection Moon'],
            ['cardmarket_expansion_id' => 5901, 'name' => 'XY-P Promotional cards'],
            ['cardmarket_expansion_id' => 5900, 'name' => 'Evolutions (Japan)'],
            ['cardmarket_expansion_id' => 5899, 'name' => 'The Best of XY'],
            ['cardmarket_expansion_id' => 5898, 'name' => 'Cruel Traitor'],
            ['cardmarket_expansion_id' => 5897, 'name' => 'Fever-Burst Fighter'],
            ['cardmarket_expansion_id' => 5896, 'name' => 'M Audino-EX Mega Battle Deck'],
            ['cardmarket_expansion_id' => 5895, 'name' => 'BREAK Evolution Box'],
            ['cardmarket_expansion_id' => 5894, 'name' => 'Golduck BREAK Evolution Pack'],
            ['cardmarket_expansion_id' => 5893, 'name' => 'Rage of the Broken Heavens'],
            ['cardmarket_expansion_id' => 5892, 'name' => 'Awakening Psychic King'],
            ['cardmarket_expansion_id' => 5891, 'name' => 'Premium Champion Pack'],
            ['cardmarket_expansion_id' => 5890, 'name' => 'Red Flash'],
            ['cardmarket_expansion_id' => 5889, 'name' => 'Blue Shock'],
            ['cardmarket_expansion_id' => 5888, 'name' => 'Grass/Lightning Battle Strength Set'],
            ['cardmarket_expansion_id' => 5887, 'name' => 'Fire/Water Battle Strength Set'],
            ['cardmarket_expansion_id' => 5886, 'name' => 'Raichu BREAK Evolution Pack'],
            ['cardmarket_expansion_id' => 5885, 'name' => 'XY BREAK Battle Booster Pack'],
            ['cardmarket_expansion_id' => 5884, 'name' => 'XY BREAK Starter Pack'],
            ['cardmarket_expansion_id' => 5883, 'name' => 'Legendary Shine Collection'],
            ['cardmarket_expansion_id' => 5882, 'name' => 'Legendary Holo Collection'],
            ['cardmarket_expansion_id' => 5881, 'name' => 'Bandit Ring'],
            ['cardmarket_expansion_id' => 5880, 'name' => 'Emerald Break'],
            ['cardmarket_expansion_id' => 5879, 'name' => 'M Master Deck Build Box Power Style'],
            ['cardmarket_expansion_id' => 5878, 'name' => 'M Master Deck Build Box Speed Style'],
            ['cardmarket_expansion_id' => 5877, 'name' => 'Blue Impact'],
            ['cardmarket_expansion_id' => 5876, 'name' => 'Red Flash (Japan)'],
            ['cardmarket_expansion_id' => 5875, 'name' => 'Tidal Storm'],
            ['cardmarket_expansion_id' => 5874, 'name' => 'Gaia Volcano'],
            ['cardmarket_expansion_id' => 5873, 'name' => 'Double Crisis'],
            ['cardmarket_expansion_id' => 5872, 'name' => 'Phantom Gate'],
            ['cardmarket_expansion_id' => 5871, 'name' => 'Super Legend Set: Xerneas EX & Yveltal EX'],
            ['cardmarket_expansion_id' => 5870, 'name' => 'Rising Fist'],
            ['cardmarket_expansion_id' => 5869, 'name' => 'M Charizard-EX Mega Battle Deck'],
            ['cardmarket_expansion_id' => 5868, 'name' => 'Hyper Metal Chain Deck 60: Dialga-EX + Aegislash-EX'],
            ['cardmarket_expansion_id' => 5867, 'name' => 'Xerneas Half Deck'],
            ['cardmarket_expansion_id' => 5866, 'name' => 'Yveltal Half Deck'],
            ['cardmarket_expansion_id' => 5865, 'name' => 'Wild Blaze'],
            ['cardmarket_expansion_id' => 5864, 'name' => 'XY Beginning Set'],
            ['cardmarket_expansion_id' => 5863, 'name' => 'Collection Y'],
            ['cardmarket_expansion_id' => 5862, 'name' => 'Collection X'],
            ['cardmarket_expansion_id' => 5861, 'name' => 'BW-P Promotional cards'],
            ['cardmarket_expansion_id' => 5860, 'name' => 'Legendary Treasures (Japan)'],
            ['cardmarket_expansion_id' => 5859, 'name' => 'EX Battle Boost (Japan)'],
            ['cardmarket_expansion_id' => 5858, 'name' => 'Megalo Cannon'],
            ['cardmarket_expansion_id' => 5857, 'name' => 'Master Deck Build Box EX'],
            ['cardmarket_expansion_id' => 5856, 'name' => 'Plasma Gale'],
            ['cardmarket_expansion_id' => 5855, 'name' => 'Shiny Collection'],
            ['cardmarket_expansion_id' => 5854, 'name' => 'Spiral Force'],
            ['cardmarket_expansion_id' => 5853, 'name' => 'Thunder Knuckle'],
            ['cardmarket_expansion_id' => 5852, 'name' => 'EX Battle Boost'],
            ['cardmarket_expansion_id' => 5851, 'name' => 'Team Plasma Battle Gift Set'],
            ['cardmarket_expansion_id' => 5850, 'name' => 'Cold Flare'],
            ['cardmarket_expansion_id' => 5849, 'name' => 'Freeze Bolt'],
            ['cardmarket_expansion_id' => 5848, 'name' => 'Dragon Blade'],
            ['cardmarket_expansion_id' => 5847, 'name' => 'Dragon Blast'],
            ['cardmarket_expansion_id' => 5846, 'name' => 'BW Battle Strength Decks'],
            ['cardmarket_expansion_id' => 5843, 'name' => 'Dark Rush'],
            ['cardmarket_expansion_id' => 5842, 'name' => 'Psycho Drive'],
            ['cardmarket_expansion_id' => 5841, 'name' => 'Hail Blizzard'],
            ['cardmarket_expansion_id' => 5840, 'name' => 'Reshiram-EX Battle Strength Deck'],
            ['cardmarket_expansion_id' => 5839, 'name' => 'Zekrom-EX Battle Strength Deck'],
            ['cardmarket_expansion_id' => 5838, 'name' => 'Red Collection'],
            ['cardmarket_expansion_id' => 5837, 'name' => 'Black Collection'],
            ['cardmarket_expansion_id' => 5836, 'name' => 'Emerging Powers (Japan)'],
            ['cardmarket_expansion_id' => 5835, 'name' => 'Battle Gift Set: Thundurus vs Tornadus'],
            ['cardmarket_expansion_id' => 5834, 'name' => 'White Collection'],
            ['cardmarket_expansion_id' => 5833, 'name' => 'Green Collection'],
            ['cardmarket_expansion_id' => 5832, 'name' => 'Blue Collection'],
            ['cardmarket_expansion_id' => 5831, 'name' => 'DP-P Promotional cards'],
            ['cardmarket_expansion_id' => 5830, 'name' => 'Clash at the Summit'],
            ['cardmarket_expansion_id' => 5829, 'name' => 'L-P Promotional cards'],
            ['cardmarket_expansion_id' => 5828, 'name' => 'Leafeon vs Metagross Half Deck'],
            ['cardmarket_expansion_id' => 5827, 'name' => 'Lost Link'],
            ['cardmarket_expansion_id' => 5826, 'name' => 'Tyranitar Half Deck'],
            ['cardmarket_expansion_id' => 5825, 'name' => 'Reviving Legends'],
            ['cardmarket_expansion_id' => 5824, 'name' => 'Expert Deck: Leafeon vs Metagross'],
            ['cardmarket_expansion_id' => 5823, 'name' => 'Advent of Arceus'],
            ['cardmarket_expansion_id' => 5822, 'name' => 'Gift Box: Meowth and Pikachu'],
            ['cardmarket_expansion_id' => 5821, 'name' => 'Gift Box: Tangrowth and Dusknoir'],
            ['cardmarket_expansion_id' => 5820, 'name' => 'DPt-P Promotional cards'],
            ['cardmarket_expansion_id' => 5819, 'name' => 'Supreme Victors (Japan)'],
            ['cardmarket_expansion_id' => 5818, 'name' => 'Rising Rivals (Japan)'],
            ['cardmarket_expansion_id' => 5817, 'name' => 'Movie Commemoration Random Pack'],
            ['cardmarket_expansion_id' => 5816, 'name' => 'Bonds to the End of Time'],
            ['cardmarket_expansion_id' => 5815, 'name' => 'Entry Pack DPt'],
            ['cardmarket_expansion_id' => 5814, 'name' => 'Cry from the Mysterious'],
            ['cardmarket_expansion_id' => 5813, 'name' => 'Galactic\'s Conquest'],
            ['cardmarket_expansion_id' => 5812, 'name' => 'Intense Fight in the Destroyed Sky'],
            ['cardmarket_expansion_id' => 5811, 'name' => 'Temple of Anger'],
            ['cardmarket_expansion_id' => 5810, 'name' => 'Moonlit Pursuit'],
            ['cardmarket_expansion_id' => 5809, 'name' => 'Shaymin LV.X Collection Pack'],
            ['cardmarket_expansion_id' => 5808, 'name' => 'Mystery of the Lakes'],
            ['cardmarket_expansion_id' => 5807, 'name' => 'Dialga LV.X Constructed Starter Deck'],
            ['cardmarket_expansion_id' => 5806, 'name' => 'Palkia LV.X Constructed Starter Deck'],
            ['cardmarket_expansion_id' => 5805, 'name' => 'Shining Darkness'],
            ['cardmarket_expansion_id' => 5804, 'name' => 'Dawn Dash'],
            ['cardmarket_expansion_id' => 5803, 'name' => 'Night Dashing'],
            ['cardmarket_expansion_id' => 5802, 'name' => 'Space-Time Creation'],
            ['cardmarket_expansion_id' => 5801, 'name' => 'PCG-P Promotional cards'],
            ['cardmarket_expansion_id' => 5799, 'name' => 'Magmortar Half Deck'],
            ['cardmarket_expansion_id' => 5798, 'name' => 'Electivire Half Deck'],
            ['cardmarket_expansion_id' => 5797, 'name' => 'World Champions Pack'],
            ['cardmarket_expansion_id' => 5796, 'name' => 'Shockwave + Jet Flame'],
            ['cardmarket_expansion_id' => 5795, 'name' => 'Porygon-Z LV.X Movie Commemoration'],
            ['cardmarket_expansion_id' => 5794, 'name' => 'DP6 Movie Commemoration'],
            ['cardmarket_expansion_id' => 5793, 'name' => 'Dialga LV.X Constructed Standard Deck'],
            ['cardmarket_expansion_id' => 5792, 'name' => 'Palkia LV.X Constructed Standard Deck'],
            ['cardmarket_expansion_id' => 5791, 'name' => 'Entry Pack'],
            ['cardmarket_expansion_id' => 5790, 'name' => 'Moonlight Pursuit'],
            ['cardmarket_expansion_id' => 5789, 'name' => 'Melee Fierce Fight'],
            ['cardmarket_expansion_id' => 5788, 'name' => 'Secret of the Lakes'],
            ['cardmarket_expansion_id' => 5787, 'name' => 'Glittering Darkness'],
            ['cardmarket_expansion_id' => 5786, 'name' => 'Inferno + Frost Bolt'],
            ['cardmarket_expansion_id' => 5785, 'name' => 'Giratina Half Deck'],
            ['cardmarket_expansion_id' => 5784, 'name' => 'Space-Time Distortion'],
            ['cardmarket_expansion_id' => 5783, 'name' => 'ADV-P Promotional cards'],
            ['cardmarket_expansion_id' => 5782, 'name' => 'Shockwave + Jet Flame (Japan)'],
            ['cardmarket_expansion_id' => 5781, 'name' => 'Blastoise + Venusaur Constructed Starter Deck'],
            ['cardmarket_expansion_id' => 5780, 'name' => 'Charizard + Raichu Constructed Starter Deck'],
            ['cardmarket_expansion_id' => 5779, 'name' => 'Movie 10th Anniversary Premium Sheet'],
            ['cardmarket_expansion_id' => 5778, 'name' => 'Movie 10th Anniversary Set: Pokémon Card Game vs'],
            ['cardmarket_expansion_id' => 5777, 'name' => 'Movie 10th Anniversary Set: Pokémon Card Game DP'],
            ['cardmarket_expansion_id' => 5776, 'name' => 'Movie 10th Anniversary Set: Pokémon Card Game ADV'],
            ['cardmarket_expansion_id' => 5775, 'name' => 'Pikachu The Movie 2007 Gift Box'],
            ['cardmarket_expansion_id' => 5774, 'name' => 'Movie Commemoration VS Pack: Sea'],
            ['cardmarket_expansion_id' => 5773, 'name' => 'Movie Commemoration VS Pack: Sky'],
            ['cardmarket_expansion_id' => 5772, 'name' => 'Movie Random Pack'],
            ['cardmarket_expansion_id' => 5771, 'name' => 'Miracle Crystal'],
            ['cardmarket_expansion_id' => 5770, 'name' => 'DP Battle Starter Deck'],
            ['cardmarket_expansion_id' => 5769, 'name' => 'World Championship Series'],
            ['cardmarket_expansion_id' => 5768, 'name' => 'Flight of Legends'],
            ['cardmarket_expansion_id' => 5767, 'name' => 'Battle Road Autumn Prize'],
            ['cardmarket_expansion_id' => 5766, 'name' => 'Battle Road Summer Prize'],
            ['cardmarket_expansion_id' => 5765, 'name' => 'Battle Road Spring Prize'],
            ['cardmarket_expansion_id' => 5764, 'name' => 'Tyranitar Constructed Starter Deck'],
            ['cardmarket_expansion_id' => 5763, 'name' => 'Garchomp Constructed Starter Deck'],
            ['cardmarket_expansion_id' => 5762, 'name' => 'Bastiodon Constructed Starter Deck'],
            ['cardmarket_expansion_id' => 5761, 'name' => 'Rampardos Constructed Starter Deck'],
            ['cardmarket_expansion_id' => 5760, 'name' => 'Burning Crusade'],
            ['cardmarket_expansion_id' => 5759, 'name' => 'Thundering Rumble'],
            ['cardmarket_expansion_id' => 5758, 'name' => 'Darkrai Half Deck'],
            ['cardmarket_expansion_id' => 5757, 'name' => 'Electivire vs Magmortar Constructed Standard Deck'],
            ['cardmarket_expansion_id' => 5756, 'name' => 'Manaphy + Lucario Theme Deck'],
            ['cardmarket_expansion_id' => 5755, 'name' => 'Inferno + Freeze Bolt (Japan)'],
            ['cardmarket_expansion_id' => 5754, 'name' => 'Dialga vs Palkia vs Darkrai Gift Box'],
            ['cardmarket_expansion_id' => 5753, 'name' => 'Torterra vs Infernape vs Empoleon Gift Box'],
            ['cardmarket_expansion_id' => 5752, 'name' => 'Arceus LV.X Half Deck'],
            ['cardmarket_expansion_id' => 5751, 'name' => 'Torterra vs Infernape vs Empoleon Starter Deck'],
            ['cardmarket_expansion_id' => 5750, 'name' => 'Victini vs Hydreigon Half Deck'],
            ['cardmarket_expansion_id' => 5749, 'name' => 'Empoleon Half Deck'],
            ['cardmarket_expansion_id' => 5748, 'name' => 'Infernape Half Deck'],
            ['cardmarket_expansion_id' => 5747, 'name' => 'Torterra Half Deck'],
            ['cardmarket_expansion_id' => 5746, 'name' => 'Grass + Lightning (Japan)'],
            ['cardmarket_expansion_id' => 5745, 'name' => 'Fire + Water (Japan)'],
            ['cardmarket_expansion_id' => 5744, 'name' => 'Call of Legends (Japan)'],
            ['cardmarket_expansion_id' => 5743, 'name' => 'Triumphant (Japan)'],
            ['cardmarket_expansion_id' => 5742, 'name' => 'Undaunted (Japan)'],
            ['cardmarket_expansion_id' => 5741, 'name' => 'Unleashed (Japan)'],
            ['cardmarket_expansion_id' => 5740, 'name' => 'HS Base Set (Japan)'],
            ['cardmarket_expansion_id' => 5739, 'name' => 'SoulSilver + HeartGold Half Deck'],
            ['cardmarket_expansion_id' => 5738, 'name' => 'HeartGold + SoulSilver Theme Deck'],
            ['cardmarket_expansion_id' => 5737, 'name' => 'Mewtwo Half Deck'],
            ['cardmarket_expansion_id' => 5736, 'name' => 'Mew Half Deck'],
            ['cardmarket_expansion_id' => 5735, 'name' => 'Torterra LV.X Half Deck'],
            ['cardmarket_expansion_id' => 5734, 'name' => 'Infernape LV.X Half Deck'],
            ['cardmarket_expansion_id' => 5733, 'name' => 'Empoleon LV.X Half Deck'],
            ['cardmarket_expansion_id' => 5732, 'name' => 'Leafeon vs Metagross Deck'],
            ['cardmarket_expansion_id' => 5731, 'name' => 'Giratina vs Dialga vs Palkia Gift Box'],
            ['cardmarket_expansion_id' => 5730, 'name' => 'Quick Construction Packs'],
            ['cardmarket_expansion_id' => 5729, 'name' => 'Clash at the Summit (Japan)'],
            ['cardmarket_expansion_id' => 5728, 'name' => 'Galactic\'s Conquest (Japan)'],
            ['cardmarket_expansion_id' => 5727, 'name' => 'Advent of Arceus (Japan)'],
            ['cardmarket_expansion_id' => 5726, 'name' => 'Luminous Rampage'],
            ['cardmarket_expansion_id' => 5725, 'name' => 'Reviving Legends (Japan)'],
            ['cardmarket_expansion_id' => 5724, 'name' => 'Bonds to the End of Time (Japan)'],
            ['cardmarket_expansion_id' => 5723, 'name' => 'Intense Fight in Destroyed Sky (Japan)'],
            ['cardmarket_expansion_id' => 5722, 'name' => 'Cry from the Mysterious (Japan)'],
            ['cardmarket_expansion_id' => 5721, 'name' => 'Shining Darkness (Japan)'],
            ['cardmarket_expansion_id' => 5720, 'name' => 'Dawn Dash (Japan)'],
            ['cardmarket_expansion_id' => 5719, 'name' => 'Dialga LV.X vs Palkia LV.X Deck vs Set'],
            ['cardmarket_expansion_id' => 5718, 'name' => 'Garchomp vs Charizard Battle Deck'],
            ['cardmarket_expansion_id' => 5717, 'name' => 'Mewtwo vs Genesect Battle Deck'],
            ['cardmarket_expansion_id' => 5716, 'name' => 'Groudon vs Kyogre Battle Deck'],
            ['cardmarket_expansion_id' => 5715, 'name' => 'Arceus Battle Deck'],
            ['cardmarket_expansion_id' => 5714, 'name' => 'Legendary Heartbeat: Amazing Volt Tackle'],
            ['cardmarket_expansion_id' => 5713, 'name' => 'Rayquaza vs Mewtwo Battle Deck'],
            ['cardmarket_expansion_id' => 5712, 'name' => 'Regigigas vs Dialga vs Palkia Battle Deck'],
            ['cardmarket_expansion_id' => 5711, 'name' => 'Dragonite vs Garchomp Battle Deck'],
            ['cardmarket_expansion_id' => 5710, 'name' => 'Lugia vs Ho-Oh Battle Deck'],
            ['cardmarket_expansion_id' => 5709, 'name' => 'Zekrom vs Reshiram Battle Deck'],
            ['cardmarket_expansion_id' => 5708, 'name' => 'Kyurem vs Sacred Swordsmen Battle Deck'],
            ['cardmarket_expansion_id' => 5707, 'name' => 'Movie Rampage! Mega Rayquaza vs Mega Diancie'],
            ['cardmarket_expansion_id' => 5706, 'name' => 'Lucario vs Zoroark Battle Deck'],
            ['cardmarket_expansion_id' => 5705, 'name' => 'Mega Lucario vs Mega Gengar Battle Deck'],
            ['cardmarket_expansion_id' => 5704, 'name' => 'Xerneas vs Yveltal Battle Deck'],
            ['cardmarket_expansion_id' => 5703, 'name' => 'Mega Blastoise vs Mega Venusaur Battle Deck'],
            ['cardmarket_expansion_id' => 5702, 'name' => 'Kyogre vs Groudon Battle Deck'],
            ['cardmarket_expansion_id' => 5701, 'name' => 'Reshiram vs Zekrom Battle Deck'],
            ['cardmarket_expansion_id' => 5700, 'name' => 'Kyurem vs Sacred Swordsmen Battle Deck (Japan)'],
            ['cardmarket_expansion_id' => 5699, 'name' => 'Lugia Ho-Oh Battle Deck'],
            ['cardmarket_expansion_id' => 5698, 'name' => 'Dragonite vs Garchomp Battle Deck (Japan)'],
            ['cardmarket_expansion_id' => 5695, 'name' => 'Tag All Stars'],
            ['cardmarket_expansion_id' => 5694, 'name' => 'Snorlax VMAX Special Deck Set'],
            ['cardmarket_expansion_id' => 5693, 'name' => 'Eevee Heroes Premium Trainer Box'],
            ['cardmarket_expansion_id' => 5692, 'name' => '25th Anniversary Collection'],
            ['cardmarket_expansion_id' => 5691, 'name' => 'Zacian + Zamazenta Box'],
            ['cardmarket_expansion_id' => 5690, 'name' => 'Shiny Star V'],
            ['cardmarket_expansion_id' => 5689, 'name' => 'Starter Set VMAX Venusaur'],
            ['cardmarket_expansion_id' => 5688, 'name' => 'Starter Set VMAX Charizard'],
            ['cardmarket_expansion_id' => 5687, 'name' => 'Starter Set VMAX Blastoise'],
            ['cardmarket_expansion_id' => 5686, 'name' => 'V Starter Decks'],
            ['cardmarket_expansion_id' => 5685, 'name' => 'Starter Set V Lightning'],
            ['cardmarket_expansion_id' => 5684, 'name' => 'Starter Set V Fighting'],
            ['cardmarket_expansion_id' => 5683, 'name' => 'Starter Set V Water'],
            ['cardmarket_expansion_id' => 5682, 'name' => 'Starter Set V Grass'],
            ['cardmarket_expansion_id' => 5681, 'name' => 'Starter Set V Fire'],
            ['cardmarket_expansion_id' => 5680, 'name' => 'High Class Pack GX Ultra Shiny'],
            ['cardmarket_expansion_id' => 5679, 'name' => 'High Class Pack TAG TEAM GX Tag All Stars'],
            ['cardmarket_expansion_id' => 5678, 'name' => 'Charizard & Grimmsnarl VMAX Starter Set'],
            ['cardmarket_expansion_id' => 5677, 'name' => 'Pikachu & Zekrom-GX Special Art Box'],
            ['cardmarket_expansion_id' => 5676, 'name' => 'Legendary Heartbeat: Charizard VMAX Starter Set'],
            ['cardmarket_expansion_id' => 5675, 'name' => 'Family Pokemon Card Game'],
            ['cardmarket_expansion_id' => 5674, 'name' => 'V Start Deck Lightning Pikachu V'],
            ['cardmarket_expansion_id' => 5673, 'name' => 'V Start Deck Fighting Riolu'],
            ['cardmarket_expansion_id' => 5672, 'name' => 'V Start Deck Water Sobble'],
            ['cardmarket_expansion_id' => 5671, 'name' => 'V Start Deck Grass Grookey'],
            ['cardmarket_expansion_id' => 5670, 'name' => 'V Start Deck Fire Scorbunny'],
            ['cardmarket_expansion_id' => 5665, 'name' => 'Detective Pikachu'],
            ['cardmarket_expansion_id' => 5664, 'name' => 'SM12a TAG TEAM GX Tag All Stars'],
            ['cardmarket_expansion_id' => 5663, 'name' => 'SM11b Dream League'],
            ['cardmarket_expansion_id' => 5662, 'name' => 'SM11a Remix Bout'],
            ['cardmarket_expansion_id' => 5661, 'name' => 'SM10b Sky Legend'],
            ['cardmarket_expansion_id' => 5660, 'name' => 'SM10a GG End'],
            ['cardmarket_expansion_id' => 5659, 'name' => 'SM9b Full Metal Wall'],
            ['cardmarket_expansion_id' => 5658, 'name' => 'SM9a Night Unison'],
            ['cardmarket_expansion_id' => 5657, 'name' => 'SM8b GX Ultra Shiny'],
            ['cardmarket_expansion_id' => 5656, 'name' => 'SM8a Dark Order'],
            ['cardmarket_expansion_id' => 5655, 'name' => 'SM7b Fairy Rise'],
            ['cardmarket_expansion_id' => 5654, 'name' => 'SM7a Thunderclap Spark'],
            ['cardmarket_expansion_id' => 5653, 'name' => 'SM6b Champion Road'],
            ['cardmarket_expansion_id' => 5652, 'name' => 'SM6a Dragon Storm'],
            ['cardmarket_expansion_id' => 5651, 'name' => 'SM5+ Ultra Force'],
            ['cardmarket_expansion_id' => 5650, 'name' => 'SM4+ GX Battle Boost'],
            ['cardmarket_expansion_id' => 5649, 'name' => 'SM3+ Shining Legends'],
            ['cardmarket_expansion_id' => 5648, 'name' => 'SM2+ Beyond a New Challenge'],
            ['cardmarket_expansion_id' => 5647, 'name' => 'SM1+ Sun & Moon Strengthening Expansion Pack'],
            ['cardmarket_expansion_id' => 5646, 'name' => 'SM-P Promotional Cards'],
        ];

        DB::table('cardmarket_expansions')->insert($expansions);
    }
}
